### ISSUE TITLE
Create Exploration Notebook

### ISSUE THREAD

**Issue by janikmu** [janiksudo/PDS_Project#16]
that summarizes steps taken in preprocessing and analyzing of the raw data.

We should create one branch for that!

**Comment by janikmu** [comment]
Start: @tockenga 
Wenn du fertig bist, schreib hier und verlink den nächsten.

**Comment by tockenga** [comment]
Ich habe ein entsprechendes Notebook erstellt sowie zusätzliche Zeilen in der clean_data Methode ergänzt. Außerdem habe ich in der create_trips Methode berichtigt, dass nur noch Rundtrips die unter 3 Minuten liegen rausgeschmissen werden. @janiksudo du kannst weitermachen und wenn es geht das Attribut PLZ sowie geometry in trips.csv aufnehmen.

**Comment by janikmu** [comment]
Geometry wird schwierig, da das GeoDataFrame nur eine geometry Spalte haben kann und ich ja Start und Endpunkt als POINT Geometry habe.

**Comment by tockenga** [comment]
> Geometry wird schwierig, da das GeoDataFrame nur eine geometry Spalte haben kann und ich ja Start und Endpunkt als POINT Geometry habe.

Verstehe, dann lass es ruhig raus. Es ist einfach später die entsprechenden GPDs zu erstellen.

**Comment by janikmu** [comment]
@Dianagw Bühne frei für dich.

**Comment by Dianagw** [comment]
@Channaholic Du bist nun dran :) 
@janiksudo meine most popular roads haben sich geändert. Das sind alles nur noch round trips.

**Comment by Channaholic** [comment]
Habe monthly distributions geadded. @mildlyinteresting

**Comment by janikmu** [comment]
> @janiksudo meine most popular roads haben sich geändert. Das sind alles nur noch round trips.

Hm, das ist natürlich blöd. Vielleicht sollten wir dann doch auch alle Rundtrips zu Stationen rausschmeißen. Ich hatte gehofft das gibt sich wenn man extrem lange Rundtrips rausschmeißt (was ich noch nicht gemacht hatte)...

**Comment by janikmu** [comment]
@Channaholic Deine Monate Oktober und November sind gleich bei day_of_month Plots. Liegt daran dass du die Variable fast immer day_of_month_jan genannt hast du fauler Mensch 😂

**Comment by janikmu** [comment]
Aber sprecht euch ab @Channaholic @mildlyinteresting damit's keine Merge Konflikte gibt.
