### ISSUE TITLE
Create a trip data frame

### ISSUE THREAD

**Issue by tockenga** [janiksudo/PDS_Project#9]
Create a new DataFrame that stores (at least) the following trip information (“trip format”):

- Bike number
- Start time
- Weekend
- Start Position
- Duration
- End Time
- End Position

Add more columns but explain why helpful for later analysis.

processed/bremen_cleaned.csv -> processed/trips_bremen.csv

**Comment by janikmu** [comment]
Revisit: When calling transform on a csv in the CLI, this must use the preprocessor to transform and store to trip dataframe

Preprocessor has also to be slightly changed to introduce "weekend" as a True/False feature.

Also maybe introduce something like `verbose=True/False` as a parameter to the Preprocessor. We want a more verbose dataframe (weather etc) whereas calling `transform new.csv` in the CLI should yield the trip dataframe detailed above (a non-verbose version)?

**Comment by janikmu** [comment]
done in #24, closing
